import { Request, Response } from 'express';
import Message from '../../database/models/Message.model';
import Design from '../../database/models/Design.model';
import DesignFile, { FileType as ModelFileType } from '../../database/models/DesignFile.model';
import { User } from '../../database/models/User.model';
import db from '../../database/Configuration.db';
import { validateArchitecturalContent } from '../../utils/architecturalValidator';
import { DesignFileService } from '../../services/ai/DesignFileService';
import MainAIService from '../../services/ai/MainAIService';
import { ArchitecturalPrompt } from '../../services/ai/ConfigAI';
import { ArchitecturalValidator } from '../../middlewares/validation/ArchitecturalValidator';
import OpenAIArchitecturalService from '../../services/ai/OpenAIArchitecturalService';
import { v4 as uuidv4 } from 'uuid';
import { Op } from 'sequelize';
import * as fs from 'fs'; 
import * as path from 'path'; 

type ArchitecturalFileType = '2d' | '3d' | 'render' | 'document'; 
type BuildingType = '2d' | '3d' | 'both';
type Complexity = 'simple' | 'medium' | 'complex';

interface Room {
  type: string;
  count: number;
  minArea?: number;
}

function getModelFileType(architecturalType: ArchitecturalFileType, format: string): ModelFileType {
  const typeMapping: Record<ArchitecturalFileType, Record<string, ModelFileType>> = {
    '2d': {
      'PDF': 'pdf',
      'DWG': 'dwg',
      'DXF': 'dxf',
      'JPG': 'image',
      'PNG': 'image'
    },
    '3d': {
      'OBJ': 'obj',
      'FBX': 'fbx',
      'GLTF': 'gltf',
      'SKP': 'skp'
    },
    'render': {
      'JPG': 'image',
      'PNG': 'image'
    },
    'document': {
      'PDF': 'pdf',
      'JSON': 'json'
    }
  };
  
  return typeMapping[architecturalType]?.[format] || 'pdf';
}

interface ArchitecturalAnalysis {
  requirements: {
    totalArea: number;
    rooms: Room[];
    specialFeatures: string[];
    style?: string;
    budget?: string;
  };
  designParameters: {
    buildingType: BuildingType;
    complexity: Complexity;
    priority: 'speed' | 'quality' | 'cost'; 
  };
  autoGeneration: {
    shouldGenerate: boolean;
    suggestedFormats: string[];
    estimatedTime: string;
  };
}

interface AIArchitecturalResponse {
  analysis: ArchitecturalAnalysis;
  designConcept: string;
  technicalSpecs: {
    dimensions: string;
    layout: string;
    structuralNotes: string;
  };
  autoGeneratedFiles: Array<{
    type: string;
    format: string;
    status: 'generating' | 'queued';
    estimatedTime: string;
  }>;
  conversationFlow: {
    nextSteps: string[];
    clarificationQuestions: string[];
    readyForGeneration: boolean;
  };
}

export const sendArchitecturalMessage = async (req: Request, res: Response) => {
    try {
        const { designUuid } = req.params;
        const { content, role } = req.body;
        const userId = req.userId;

        // 🛡️ VALIDACIÓN DE CONTEXTO ARQUITECTÓNICO EN BACKEND
        if (role === 'user') {
            const validation = validateArchitecturalContent(content);
            
            if (!validation.isValid) {
                // Crear mensaje de respuesta del asistente explicando el error
                const errorMessage = {
                    uuid: generateUUID(),
                    role: 'assistant',
                    content: `🤖 ${validation.reason}\n\n💡 Soy un asistente especializado en diseño arquitectónico. Puedo ayudarte con:\n• Diseño de casas, departamentos y edificios\n• Planos arquitectónicos y técnicos\n• Modelos 3D y renders\n• Cálculos de espacios y distribución\n• Selección de materiales y estilos\n\n📋 Por favor, describe tu proyecto arquitectónico con detalles como: tipo de construcción, número de habitaciones, área, estilo, etc.`,
                    status: 'completed',
                    createdAt: new Date().toISOString()
                };

                return res.status(400).json({
                    success: false,
                    message: validation.reason,
                    data: {
                        message: errorMessage,
                        validation: {
                            isValid: false,
                            context: 'architectural_only',
                            requiredElements: [
                                'Tipo de construcción (casa, edificio, oficina, etc.)',
                                'Número de espacios o habitaciones',
                                'Área aproximada en metros cuadrados',
                                'Estilo arquitectónico preferido',
                                'Características especiales deseadas'
                            ]
                        }
                    },
                    action: 'validation_failed'
                });
            }
        }

        // Verificar diseño
        const design = await Design.findOne({
            where: { 
                uuid: designUuid,
                userId: userId 
            }
        });

        if (!design) {
            return res.status(404).json({
                success: false,
                message: "Diseño no encontrado"
            });
        }

        // Crear mensaje del usuario
        const userMessage = await Message.create({
            uuid: generateUUID(),
            designId: designUuid,
            role: role || 'user',
            content: content,
            status: 'completed',
            metadata: {
                timestamp: new Date().toISOString(),
                userAgent: req.get('User-Agent') || 'unknown'
            }
        });

        // 🎯 ANÁLISIS ARQUITECTÓNICO
        const analysis = await analyzeArchitecturalRequest(content);
        
        // 🎯 GENERAR RESPUESTA CON AI
        const aiArchitecturalResponse = await generateArchitecturalResponse(analysis, design);

        // Crear mensaje de respuesta
        const aiMessage = await Message.create({
            uuid: generateUUID(),
            designId: designUuid,
            role: 'assistant',
            content: aiArchitecturalResponse.designConcept,
            status: 'completed',
            metadata: {
                timestamp: new Date().toISOString(),
                aiModel: 'architectural-assistant',
                analysis: aiArchitecturalResponse.analysis
            }
        });

        // 🎯 GENERAR PLAN ARQUITECTÓNICO COMPLETO SI ES NECESARIO
        if (analysis.autoGeneration.shouldGenerate && design.status === 'active') {
            try {
                console.log('🔄 Iniciando generación arquitectónica completa con OpenAI...');
                
                // Crear directorio temporal para archivos
                const outputDirectory = path.join(process.cwd(), 'uploads', 'designs', designUuid);
                
                // Asegurar que el directorio existe
                if (!fs.existsSync(outputDirectory)) {
                    fs.mkdirSync(outputDirectory, { recursive: true });
                }

                // 🎯 GENERAR PLAN ARQUITECTÓNICO CON OPENAI
                const nlpResult = await OpenAIArchitecturalService.processNLPToFiles(
                    content,
                    designUuid, // Usar el UUID real del diseño
                    outputDirectory
                );
                
                // Crear entradas en DesignFile para cada archivo generado
                const createdFiles = [];
                
                // Archivo SVG (2D)
                if (nlpResult.files.svg && fs.existsSync(nlpResult.files.svg)) {
                    const svgStats = fs.statSync(nlpResult.files.svg);
                    const svgFileUuid = uuidv4();
                    const svgFile = await DesignFile.create({
                        uuid: svgFileUuid,
                        filename: path.basename(nlpResult.files.svg),
                        originalName: `plan_2d.svg`,
                        fileType: 'svg' as ModelFileType,
                        fileSize: svgStats.size,
                        filePath: nlpResult.files.svg,
                        downloadUrl: `/api/files/download/${svgFileUuid}`,
                        downloadCount: 0,
                        status: 'ready',
                        designId: designUuid,
                        messageId: userMessage.uuid,
                        metadata: {
                            generatedAt: new Date().toISOString(),
                            aiGenerated: true,
                            generationMethod: 'openai-nlp',
                            fileType: '2d',
                            description: 'Plano arquitectónico 2D generado con OpenAI'
                        }
                    });
                    createdFiles.push(svgFile);
                }

                // Archivo STL (3D)
                if (nlpResult.files.stl && fs.existsSync(nlpResult.files.stl)) {
                    const stlStats = fs.statSync(nlpResult.files.stl);
                    const stlFileUuid = uuidv4();
                    const stlFile = await DesignFile.create({
                        uuid: stlFileUuid,
                        filename: path.basename(nlpResult.files.stl),
                        originalName: `model_3d.stl`,
                        fileType: 'stl' as ModelFileType,
                        fileSize: stlStats.size,
                        filePath: nlpResult.files.stl,
                        downloadUrl: `/api/files/download/${stlFileUuid}`,
                        downloadCount: 0,
                        status: 'ready',
                        designId: designUuid,
                        messageId: userMessage.uuid,
                        metadata: {
                            generatedAt: new Date().toISOString(),
                            aiGenerated: true,
                            generationMethod: 'openai-nlp',
                            fileType: '3d',
                            description: 'Modelo 3D arquitectónico generado con OpenAI'
                        }
                    });
                    createdFiles.push(stlFile);
                }

                // Actualizar estado del diseño
                await design.update({ status: 'completed' });

                // Crear mensaje de éxito
                await Message.create({
                    uuid: generateUUID(),
                    designId: designUuid,
                    role: 'assistant',
                    content: `🎉 ¡Archivos generados exitosamente con OpenAI! Se han creado ${createdFiles.length} archivos incluyendo: ${createdFiles.map((f: any) => f.fileType.toUpperCase()).join(', ')}.`,
                    status: 'completed',
                    metadata: {
                        timestamp: new Date().toISOString(),
                        aiModel: 'openai-gpt-4o-mini',
                        generationMethod: 'openai-nlp',
                        files: createdFiles.map(f => ({
                            uuid: f.uuid,
                            filename: f.filename,
                            fileType: f.fileType,
                            downloadUrl: f.downloadUrl
                        }))
                    }
                });

                console.log('✅ Archivos generados y guardados exitosamente con OpenAI');

            } catch (fileError) {
                console.error('❌ Error generando archivos con OpenAI:', fileError);
                
                await Message.create({
                    uuid: generateUUID(),
                    designId: designUuid,
                    role: 'assistant',
                    content: 'Hubo un error al generar los archivos con OpenAI. Por favor, verifica tu conexión y que la descripción contenga detalles arquitectónicos específicos.',
                    status: 'completed',
                    metadata: {
                        timestamp: new Date().toISOString(),
                        aiModel: 'openai-error',
                        error: fileError instanceof Error ? fileError.message : 'Error desconocido'
                    }
                });
            }
        }

        res.status(201).json({
            success: true,
            data: {
                message: {
                    uuid: userMessage.uuid,
                    role: userMessage.role,
                    content: userMessage.content,
                    status: userMessage.status,
                    createdAt: userMessage.createdAt
                },
                aiResponse: {
                    uuid: aiMessage.uuid,
                    content: aiMessage.content,
                    analysis: aiArchitecturalResponse.analysis,
                    readyForGeneration: aiArchitecturalResponse.conversationFlow.readyForGeneration
                }
            },
            message: "Mensaje enviado y procesado exitosamente"
        });

    } catch (error) {
        console.error('Error enviando mensaje:', error);
        res.status(500).json({
            success: false,
            message: "Error interno del servidor"
        });
    }
};

/**
 * 🆕 NUEVO ENDPOINT: Generar archivos 2D/3D con OpenAI NLP
 */
export const generateNLP2D3DFiles = async (req: Request, res: Response) => {
    try {
        const { designUuid } = req.params;
        const { content, generateFiles = true } = req.body;
        const userId = req.userId;

        console.log('🎨 Solicitud NLP to 2D/3D recibida:', { designUuid, generateFiles });

        // 🛡️ VALIDACIÓN DE CONTEXTO ARQUITECTÓNICO
        const validation = ArchitecturalValidator.validateArchitecturalContext(content);
        
        if (!validation.isValid) {
            return res.status(400).json({
                success: false,
                message: validation.reason,
                data: {
                    validation: {
                        isValid: false,
                        context: 'architectural_only',
                        requiredElements: [
                            'Descripción de espacios arquitectónicos',
                            'Tipo de construcción',
                            'Dimensiones o área',
                            'Distribución de habitaciones'
                        ]
                    }
                },
                action: 'validation_failed'
            });
        }

        // Verificar diseño
        const design = await Design.findOne({
            where: { 
                uuid: designUuid,
                userId: userId 
            }
        });

        if (!design) {
            return res.status(404).json({
                success: false,
                message: "Diseño no encontrado"
            });
        }

        // Crear mensaje del usuario
        const userMessage = await Message.create({
            uuid: generateUUID(),
            designId: designUuid,
            role: 'user',
            content: content,
            status: 'processing',
            metadata: {
                timestamp: new Date().toISOString(),
                userAgent: req.get('User-Agent') || 'unknown',
                nlpGeneration: true
            }
        });

        // 🎯 GENERAR ARCHIVOS CON OPENAI NLP
        try {
            // 🔧 USAR EL UUID REAL DEL DISEÑO - NO TEMPORAL
            const designId = designUuid; // Usar el UUID real del diseño
            const outputDirectory = path.join(process.cwd(), 'uploads', 'designs', designUuid);

            // Asegurar que el directorio existe
            if (!fs.existsSync(outputDirectory)) {
                fs.mkdirSync(outputDirectory, { recursive: true });
            }

            console.log('🤖 Generando archivos con OpenAI NLP...');
            console.log('📂 Directorio de salida:', outputDirectory);
            console.log('🆔 UUID del diseño:', designId);
            
            const nlpResult = await OpenAIArchitecturalService.processNLPToFiles(
                content,
                designId,
                outputDirectory
            );

            console.log('✅ Archivos NLP generados exitosamente');
            console.log('📁 Archivos creados:', nlpResult.files);

            // Actualizar mensaje como completado
            await userMessage.update({ 
                status: 'completed',
                metadata: {
                    ...userMessage.metadata,
                    nlpProcessingTime: nlpResult.processingTime
                }
            });

            console.log('📝 Mensaje de usuario actualizado');

            // Crear mensaje de respuesta del asistente
            const aiMessage = await Message.create({
                uuid: generateUUID(),
                designId: designUuid,
                role: 'assistant',
                content: `✅ **Archivos generados exitosamente con IA avanzada**\n\n🎯 **Procesamiento completado:**\n• Análisis NLP: ${nlpResult.processingTime}ms\n• Archivo 2D: ${nlpResult.files.svg ? '✅ SVG generado' : '❌ Error'}\n• Archivo 3D: ${nlpResult.files.stl ? '✅ STL generado' : '❌ Error'}\n\n📊 **Datos estructurales extraídos:**\n• Habitaciones: ${nlpResult.structuralData.rooms.length}\n• Área total: ${nlpResult.structuralData.metadata.totalArea}m²\n• Conexiones: ${nlpResult.structuralData.connections?.length || 0}\n\n💾 Los archivos están listos para descarga.`,
                status: 'completed',
                metadata: {
                    timestamp: new Date().toISOString(),
                    aiModel: 'openai-gpt-4o-mini',
                    nlpGeneration: true,
                    files: nlpResult.files
                }
            });

            console.log('🤖 Mensaje del asistente creado');

            // Crear entradas en DesignFile para cada archivo generado
            const createdFiles = [];
            
            console.log('🔍 Verificando archivos existentes...');
            console.log('SVG existe:', nlpResult.files.svg && fs.existsSync(nlpResult.files.svg));
            console.log('STL existe:', nlpResult.files.stl && fs.existsSync(nlpResult.files.stl));
            
            const dbStartTime = Date.now();
            
            // Archivo SVG (2D)
            if (nlpResult.files.svg && fs.existsSync(nlpResult.files.svg)) {
                console.log('💾 Guardando archivo SVG en base de datos...');
                const svgStats = fs.statSync(nlpResult.files.svg);
                
                try {
                    const svgFile = await DesignFile.create({
                    uuid: uuidv4(),
                    filename: path.basename(nlpResult.files.svg),
                    originalName: `${designId}_2d_plan.svg`,
                    fileType: 'svg' as ModelFileType,
                    fileSize: svgStats.size,
                    filePath: nlpResult.files.svg,
                    downloadUrl: `/api/files/download/${designUuid}/${path.basename(nlpResult.files.svg)}`,
                    downloadCount: 0,
                    status: 'ready',
                    designId: designUuid,
                    messageId: userMessage.uuid,
                    metadata: {
                        generatedAt: new Date().toISOString(),
                        aiGenerated: true,
                        generationMethod: 'openai-nlp',
                        fileType: '2d',
                        description: 'Plano arquitectónico 2D generado con IA'
                    }
                });
                createdFiles.push(svgFile);
                console.log('✅ Archivo SVG guardado en base de datos');
                } catch (svgError) {
                    console.error('❌ Error guardando SVG en BD:', svgError);
                    throw svgError;
                }
            }

            // Archivo STL (3D)
            if (nlpResult.files.stl && fs.existsSync(nlpResult.files.stl)) {
                console.log('💾 Guardando archivo STL en base de datos...');
                const stlStats = fs.statSync(nlpResult.files.stl);
                
                try {
                    const stlFile = await DesignFile.create({
                    uuid: uuidv4(),
                    filename: path.basename(nlpResult.files.stl),
                    originalName: `${designId}_3d_model.stl`,
                    fileType: 'stl' as ModelFileType,
                    fileSize: stlStats.size,
                    filePath: nlpResult.files.stl,
                    downloadUrl: `/api/files/download/${designUuid}/${path.basename(nlpResult.files.stl)}`,
                    downloadCount: 0,
                    status: 'ready',
                    designId: designUuid,
                    messageId: userMessage.uuid,
                    metadata: {
                        generatedAt: new Date().toISOString(),
                        aiGenerated: true,
                        generationMethod: 'openai-nlp',
                        fileType: '3d',
                        description: 'Modelo 3D arquitectónico generado con IA'
                    }
                });
                createdFiles.push(stlFile);
                console.log('✅ Archivo STL guardado en base de datos');
                } catch (stlError) {
                    console.error('❌ Error guardando STL en BD:', stlError);
                    throw stlError;
                }
            }

            const dbTime = Date.now() - dbStartTime;
            console.log(`📊 Total archivos creados en BD: ${createdFiles.length} (${dbTime}ms)`);

            // Actualizar estado del diseño
            console.log('🔄 Actualizando estado del diseño...');
            const designUpdateStart = Date.now();
            
            try {
                await design.update({ 
                    status: 'completed',
                    metadata: {
                        ...design.metadata,
                        lastNLPGeneration: new Date().toISOString(),
                        nlpGeneratedFiles: createdFiles.length
                    }
                });
                
                const designUpdateTime = Date.now() - designUpdateStart;
                console.log(`✅ Estado del diseño actualizado (${designUpdateTime}ms)`);
            } catch (designError) {
                console.error('❌ Error actualizando diseño:', designError);
                throw designError;
            }

            console.log('🎯 Preparando respuesta final...');
            
            // Respuesta exitosa
            const responseStart = Date.now();
            res.status(200).json({
                success: true,
                message: "Archivos 2D/3D generados exitosamente con IA",
                data: {
                    userMessage,
                    aiMessage,
                    files: createdFiles.map(file => ({
                        uuid: file.uuid,
                        filename: file.filename,
                        fileType: file.fileType,
                        fileSize: file.fileSize,
                        downloadUrl: file.downloadUrl,
                        generatedAt: (file.metadata as any)?.generatedAt || new Date().toISOString()
                    })),
                    processingStats: {
                        processingTime: nlpResult.processingTime,
                        structuralDataExtracted: !!nlpResult.structuralData,
                        roomsCount: nlpResult.structuralData.rooms.length,
                        totalArea: nlpResult.structuralData.metadata.totalArea
                    }
                },
                action: 'files_generated'
            });

            const responseTime = Date.now() - responseStart;
            console.log(`✅ Respuesta JSON enviada exitosamente al frontend (${responseTime}ms)`);

        } catch (aiError) {
            console.error('❌ Error generando archivos con OpenAI:', aiError);
            
            // Actualizar mensaje como fallido
            await userMessage.update({ 
                status: 'completed',
                metadata: {
                    ...userMessage.metadata,
                    error: aiError instanceof Error ? aiError.message : 'Error desconocido'
                }
            });

            // Retornar error sin respaldo
            return res.status(500).json({
                success: false,
                message: "Error en generación de archivos con OpenAI",
                error: aiError instanceof Error ? aiError.message : 'Error desconocido en OpenAI',
                data: {
                    userMessage,
                    troubleshooting: {
                        service: 'OpenAI',
                        recommendations: [
                            'Verifica tu conexión a internet',
                            'Confirma que la API key de OpenAI sea válida',
                            'Asegúrate de que la descripción contenga detalles arquitectónicos',
                            'Intenta con una descripción más específica'
                        ]
                    }
                }
            });
        }

    } catch (error) {
        console.error('❌ Error en generateNLP2D3DFiles:', error);
        res.status(500).json({
            success: false,
            message: "Error interno del servidor",
            error: error instanceof Error ? error.message : 'Error desconocido'
        });
    }
};

// ✅ FUNCIÓN AUXILIAR: Mapear string a ModelFileType
function getModelFileTypeFromString(fileType: string): ModelFileType {
    const mapping: Record<string, ModelFileType> = {
        'pdf': 'pdf',
        'dxf': 'dxf',
        'threejs': 'json',
        'svg': 'image'
    };
    
    return mapping[fileType] || 'pdf';
}

function generateUUID(): string {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        const r = Math.random() * 16 | 0;
        const v = c === 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });
}

//  FUNCIÓN PARA MAPEAR BUILDING TYPE A DESIGN TYPE
function mapBuildingTypeToDesignType(buildingType: BuildingType): '2d' | '3d' | 'both' {
    switch (buildingType) {
        case '2d':
            return '2d';
        case '3d':
            return '3d';
        case 'both':
            return 'both';
        default:
            return '2d'; // fallback
    }
}

// 🔧 FUNCIÓN INITIALIZEAUTOGENERATION CORREGIDA
async function initializeAutoGeneration(
  designId: string, 
  messageId: string, 
  analysis: ArchitecturalAnalysis, 
  transaction: any
) {
  const { autoGeneration } = analysis;
  
  setTimeout(async () => {
    try {
      // 🎯 PARÁMETROS CORREGIDOS
      await generateArchitecturalFile(designId, messageId, '2d', 'PDF');
      
      setTimeout(() => generateArchitecturalFile(designId, messageId, '2d', 'DWG'), 180000); // 3 min
      
      setTimeout(() => generateArchitecturalFile(designId, messageId, '3d', 'OBJ'), 300000); // 5 min
      
      setTimeout(() => generateArchitecturalFile(designId, messageId, 'render', 'JPG'), 480000); // 8 min
      
    } catch (error) {
      console.error('❌ Error en auto-generación:', error);
    }
  }, 5000); 
}

// 🔧 FUNCIÓN GENERATEARCHITECTURALFILE CORREGIDA
const generateArchitecturalFile = async (
  designId: string,
  messageId: string,
  category: ArchitecturalFileType,
  fileFormat: string
) => {
  try {
    const fileUuid = uuidv4();
    const filename = `${category}_${Date.now()}.${fileFormat.toLowerCase()}`;
    
    // 🎯 URL COMPLETA
    const downloadUrl = `${process.env.CLIENT_URL || 'http://localhost:3000'}/api/designs/files/${fileUuid}/download`;
    
    // 🎯 CREAR DIRECTORIO SI NO EXISTE
    const uploadsDir = path.join(__dirname, '../../../uploads/designs');
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }
    
    const filePath = path.join(uploadsDir, filename);
    
    // Crear archivo temporal con contenido de muestra
    const sampleContent = generateSampleFileContent(fileFormat, category);
    fs.writeFileSync(filePath, sampleContent);
    
    const actualFileSize = fs.statSync(filePath).size;

    // 🎯 MAPEAR TIPO CORRECTO PARA EL MODELO
    const modelFileType = getModelFileType(category, fileFormat);

    const designFile = await DesignFile.create({
      uuid: fileUuid,
      filename,
      originalName: filename,
      fileType: modelFileType,
      fileSize: actualFileSize,
      filePath,
      downloadUrl,
      downloadCount: 0,
      status: 'generating',
      designId,
      messageId,
      metadata: {
        category,
        format: fileFormat,
        generatedAt: new Date().toISOString(),
        aiGenerated: true
      }
    });

    // Simular progreso
    setTimeout(async () => {
      await DesignFile.update(
        { status: 'ready' },
        { where: { uuid: fileUuid } }
      );
      console.log(`✅ Archivo ${category} ${fileFormat.toUpperCase()} generado: ${filename}`);
    }, Math.random() * 3000 + 2000);

    return designFile;

  } catch (error) {
    console.error(`❌ Error generando ${category} ${fileFormat.toUpperCase()}:`, error);
    throw error;
  }
};

// 🎯 FUNCIÓN PARA GENERAR CONTENIDO DE MUESTRA
const generateSampleFileContent = (fileFormat: string, category: ArchitecturalFileType): string => {
  switch (fileFormat.toLowerCase()) {
    case 'pdf':
      return `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj
3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
>>
endobj
4 0 obj
<<
/Length 44
>>
stream
BT
/F1 12 Tf
100 700 Td
(AI Design - ${category} Generated) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000207 00000 n 
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
298
%%EOF`;

    case 'dwg':
      return `AC1021\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00AI Design ${category} File`;

    case 'obj':
      return `# AI Design ${category} File
# Generated by AI Design System
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 0.0 1.0 0.0
v 0.0 0.0 1.0
f 1 2 3
f 1 2 4
f 1 3 4
f 2 3 4`;

    case 'jpg':
      // Imagen mínima JPEG válida
      return Buffer.from([
        0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00, 0x01,
        0x01, 0x01, 0x00, 0x48, 0x00, 0x48, 0x00, 0x00, 0xFF, 0xDB, 0x00, 0x43,
        0x00, 0xFF, 0xD9
      ]).toString('binary');

    default:
      return `AI Design ${category} File - Generated Content\nFileType: ${fileFormat}\nTimestamp: ${new Date().toISOString()}`;
  }
};

async function analyzeArchitecturalRequest(content: string): Promise<ArchitecturalAnalysis> {
  const lowerContent = content.toLowerCase();
  
  const areaMatch = content.match(/(\d+)\s*m[²2]?/i);
  const totalArea = areaMatch ? parseInt(areaMatch[1]) : 0;

  const rooms: Room[] = extractRoomsFromText(content);
  const specialFeatures: string[] = extractSpecialFeatures(content);
  const buildingType = determineBuildingType(content);
  const complexity = evaluateComplexity(totalArea, rooms, specialFeatures);
  const shouldGenerate = canAutoGenerate(totalArea, rooms, complexity);

  return {
    requirements: {
      totalArea,
      rooms,
      specialFeatures,
      style: extractStyle(content),
      budget: extractBudget(content)
    },
    designParameters: {
      buildingType,
      complexity,
      priority: 'quality'
    },
    autoGeneration: {
      shouldGenerate,
      suggestedFormats: shouldGenerate ? ['PDF', 'DWG', 'OBJ', 'JPG'] : ['PDF'],
      estimatedTime: calculateEstimatedTime(complexity, shouldGenerate)
    }
  };
}

async function generateArchitecturalResponse(
  analysis: ArchitecturalAnalysis, 
  design: any
): Promise<AIArchitecturalResponse> {
  
  const { requirements, designParameters, autoGeneration } = analysis;
  
  let designConcept = `🏠 **Análisis de tu proyecto: "${design.title}"**\n\n`;
  
  designConcept += `📐 **Especificaciones detectadas:**\n`;
  designConcept += `• Área total: ${requirements.totalArea}m²\n`;
  designConcept += `• Habitaciones: ${requirements.rooms.map((r: Room) => `${r.count} ${r.type}(s)`).join(', ')}\n`;
  
  if (requirements.specialFeatures.length > 0) {
    designConcept += `• Características especiales: ${requirements.specialFeatures.join(', ')}\n`;
  }
  
  designConcept += `\n🎯 **Propuesta arquitectónica:**\n`;
  
  if (requirements.totalArea > 0 && requirements.rooms.length > 0) {
    designConcept += generateLayoutProposal(requirements);
    designConcept += `\n📋 **Especificaciones técnicas:**\n`;
    designConcept += generateTechnicalSpecs(requirements);
  }

  if (autoGeneration.shouldGenerate) {
    designConcept += `\n🚀 **Generación automática iniciada:**\n`;
    designConcept += `• Planos 2D en formato PDF y DWG\n`;
    designConcept += `• Modelo 3D en formato OBJ\n`;
    designConcept += `• Renders fotorrealistas en JPG\n`;
    designConcept += `• Tiempo estimado: ${autoGeneration.estimatedTime}\n`;
  } else {
    designConcept += `\n💬 **Necesito más información para generar los planos:**\n`;
    designConcept += `• ¿Prefieres un estilo arquitectónico específico?\n`;
    designConcept += `• ¿Hay restricciones del terreno?\n`;
    designConcept += `• ¿Qué presupuesto aproximado manejas?\n`;
  }

  const autoGeneratedFiles = autoGeneration.shouldGenerate ? [
    { type: '2d', format: 'PDF', status: 'generating' as const, estimatedTime: '2-3 min' },
    { type: '2d', format: 'DWG', status: 'queued' as const, estimatedTime: '3-4 min' },
    { type: '3d', format: 'OBJ', status: 'queued' as const, estimatedTime: '5-8 min' },
    { type: 'render', format: 'JPG', status: 'queued' as const, estimatedTime: '8-12 min' }
  ] : [];

  return {
    analysis,
    designConcept,
    technicalSpecs: {
      dimensions: generateDimensions(requirements),
      layout: generateLayout(requirements),
      structuralNotes: generateStructuralNotes(requirements)
    },
    autoGeneratedFiles,
    conversationFlow: {
      nextSteps: autoGeneration.shouldGenerate ? 
        ['wait_for_generation', 'review_files', 'request_modifications'] :
        ['provide_more_details', 'confirm_requirements', 'start_generation'],
      clarificationQuestions: generateClarificationQuestions(requirements),
      readyForGeneration: autoGeneration.shouldGenerate
    }
  };
}

// Funciones auxiliares sin cambios...
function extractRoomsFromText(content: string): Room[] {
  const rooms: Room[] = [];
  const lowerContent = content.toLowerCase();
  
  const roomPatterns = [
    { pattern: /(\d+)\s*habitaci[oó]n(es)?/, type: 'habitación' },
    { pattern: /(\d+)\s*dormitori(o|os)/, type: 'dormitorio' },
    { pattern: /(\d+)\s*ba[ñn](o|os)/, type: 'baño' },
    { pattern: /(\d+)\s*cochera(s)?/, type: 'cochera' },
    { pattern: /(\d+)\s*garaje(s)?/, type: 'garaje' },
    { pattern: /cocina/, type: 'cocina', count: 1 },
    { pattern: /sal[oó]n/, type: 'salón', count: 1 },
    { pattern: /comedor/, type: 'comedor', count: 1 },
    { pattern: /sala/, type: 'sala', count: 1 },
    { pattern: /estudio/, type: 'estudio', count: 1 }
  ];

  roomPatterns.forEach(({ pattern, type, count }) => {
    const match = lowerContent.match(pattern);
    if (match) {
      const roomCount = count || parseInt(match[1]) || 1;
      rooms.push({ type, count: roomCount });
    }
  });

  return rooms;
}

function extractSpecialFeatures(content: string): string[] {
  const features: string[] = [];
  const lowerContent = content.toLowerCase();
  
  const featurePatterns = [
    { pattern: /piscina/, feature: 'piscina' },
    { pattern: /jard[ií]n/, feature: 'jardín' },
    { pattern: /terraza/, feature: 'terraza' },
    { pattern: /balc[oó]n/, feature: 'balcón' },
    { pattern: /cochera/, feature: 'cochera' },
    { pattern: /s[oó]tano/, feature: 'sótano' },
    { pattern: /segundo piso/, feature: 'segundo piso' },
    { pattern: /cocina abierta/, feature: 'cocina abierta' },
    { pattern: /walk.?in/, feature: 'walk-in closet' }
  ];

  featurePatterns.forEach(({ pattern, feature }) => {
    if (pattern.test(lowerContent)) {
      features.push(feature);
    }
  });

  return features;
}

function determineBuildingType(content: string): BuildingType {
  const lowerContent = content.toLowerCase();
  
  if (lowerContent.includes('plano') || lowerContent.includes('2d')) {
    return '2d';
  }
  if (lowerContent.includes('modelo') || lowerContent.includes('3d')) {
    return '3d';
  }
  return 'both'; 
}

function evaluateComplexity(totalArea: number, rooms: Room[], features: string[]): Complexity {
  let score = 0;
  
  if (totalArea > 200) score += 2;
  else if (totalArea > 100) score += 1;
  
  if (rooms.length > 5) score += 2;
  else if (rooms.length > 3) score += 1;
  
  if (features.length > 3) score += 2;
  else if (features.length > 1) score += 1;
  
  if (score >= 4) return 'complex';
  if (score >= 2) return 'medium';
  return 'simple';
}

function canAutoGenerate(totalArea: number, rooms: Room[], complexity: Complexity): boolean {
  return totalArea > 0 && 
         rooms.length >= 2 && 
         complexity !== 'complex';
}

function calculateEstimatedTime(complexity: Complexity, shouldGenerate: boolean): string {
  if (!shouldGenerate) return 'Pendiente de más información';
  
  const times: Record<Complexity, string> = {
    'simple': '10-15 minutos',
    'medium': '15-25 minutos',
    'complex': '25-40 minutos'
  };
  
  return times[complexity] || '15-25 minutos';
}

function generateLayoutProposal(requirements: { totalArea: number, rooms: Room[] }): string {
  const { totalArea, rooms } = requirements;
  
  let proposal = `Distribución optimizada para ${totalArea}m²:\n`;
  
  const habitaciones = rooms.find((r: Room) => r.type === 'habitación' || r.type === 'dormitorio')?.count || 0;
  const baños = rooms.find((r: Room) => r.type === 'baño')?.count || 1;
  
  if (habitaciones > 0) {
    const areaHabitacion = Math.round((totalArea * 0.35) / habitaciones);
    proposal += `• ${habitaciones} habitación(es): ${areaHabitacion}m² c/u\n`;
  }
  
  proposal += `• Sala-comedor: ${Math.round(totalArea * 0.30)}m²\n`;
  proposal += `• Cocina: ${Math.round(totalArea * 0.12)}m²\n`;
  proposal += `• ${baños} baño(s): ${Math.round(totalArea * 0.08 / baños)}m² c/u\n`;
  proposal += `• Circulaciones: ${Math.round(totalArea * 0.15)}m²\n`;
  
  return proposal;
}

function generateTechnicalSpecs(requirements: { totalArea: number }): string {
  let specs = `• Estructura: Concreto armado\n`;
  specs += `• Cimentación: Zapatas corridas\n`;
  specs += `• Muros: Ladrillo de arcilla + tarrajeo\n`;
  specs += `• Techos: Losa aligerada h=20cm\n`;
  specs += `• Instalaciones eléctricas: 220V monofásico\n`;
  specs += `• Instalaciones sanitarias: Agua fría/caliente\n`;
  
  return specs;
}

function extractProjectTitle(content: string): string {
  if (content.includes('casa')) return 'Casa Residencial';
  if (content.includes('departamento')) return 'Departamento';
  if (content.includes('oficina')) return 'Oficina Comercial';
  return 'Proyecto Arquitectónico';
}

function extractStyle(content: string): string | undefined {
  const styles = ['moderno', 'clásico', 'minimalista', 'colonial', 'contemporáneo'];
  return styles.find(style => content.toLowerCase().includes(style));
}

function extractBudget(content: string): string | undefined {
  const budgetMatch = content.match(/(\d+)\s*(mil|millones?)/i);
  return budgetMatch ? budgetMatch[0] : undefined;
}

function generateDimensions(requirements: { totalArea: number }): string {
  const { totalArea } = requirements;
  const width = Math.sqrt(totalArea * 1.2);
  const length = totalArea / width;
  return `${Math.round(length)}m x ${Math.round(width)}m`;
}

function generateLayout(requirements: any): string {
  return 'Distribución funcional con circulaciones optimizadas';
}

function generateStructuralNotes(requirements: any): string {
  return 'Estructura convencional en concreto armado';
}

function generateClarificationQuestions(requirements: { style?: string, budget?: string, totalArea: number }): string[] {
  const questions: string[] = [];
  
  if (!requirements.style) {
    questions.push('¿Qué estilo arquitectónico prefieres?');
  }
  
  if (!requirements.budget) {
    questions.push('¿Cuál es tu presupuesto aproximado?');
  }
  
  if (requirements.totalArea === 0) {
    questions.push('¿Cuál es el área total del terreno?');
  }
  
  return questions;
}

function getMimeType(format: string): string {
  const mimeTypes: Record<string, string> = {
    'PDF': 'application/pdf',
    'DWG': 'application/acad',
    'DXF': 'application/dxf',
    'OBJ': 'application/x-tgif',
    'JPG': 'image/jpeg',
    'PNG': 'image/png'
  };
  return mimeTypes[format] || 'application/octet-stream';
}

function getProcessingTimeByType(fileType: ArchitecturalFileType, format: string): number {
  const times: Record<ArchitecturalFileType, Record<string, number>> = {
    '2d': { 'PDF': 120000, 'DWG': 180000 },
    '3d': { 'OBJ': 300000 },
    'render': { 'JPG': 480000 },
    'document': { 'PDF': 120000 }
  };
  return times[fileType]?.[format] || 120000;
}

export { 
  sendArchitecturalMessage as sendMessage,
  analyzeArchitecturalRequest,
  generateArchitecturalResponse 
};